version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: time-manager-api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=time-manager
      - GIN_MODE=debug
      - SECRET-JWT=your-secret-key-here
    depends_on:
      - db
    networks:
      - time-manager-network
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: time-manager-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=time-manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - time-manager-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: time-manager-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - time-manager-network
    restart: unless-stopped

volumes:
  postgres_data:
    name: time-manager-postgres-data

networks:
  time-manager-network:
    name: time-manager-network
    driver: bridge